language: java


jdk:
  - oraclejdk8

#before_install: 
#  - git clone -b MATH_3_X https://github.com/apache/commons-math.git ~/builds/MATH_3_X 
#  - pushd ~/builds/MATH_3_X 
#  - mvn install  
#  - popd 

#matrix:
#    allow_failures:
#        - jdk: openjdk6

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "target/orekit-9.0.jar"
  skip_cleanup: true
  on:
    tags: true
    
